# Generated by Django 4.1 on 2023-03-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'position',
            },
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('surname', models.CharField(max_length=10)),
                ('middle_name', models.CharField(max_length=10)),
                ('login', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='images/')),
                ('position', models.ManyToManyField(to='api.position')),
            ],
            options={
                'db_table': 'workers',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=10)),
                ('order_start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('worker', models.ManyToManyField(to='api.workers')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
