# Generated by Django 4.1 on 2023-03-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
