# Generated by Django 4.1 on 2023-03-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='table',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='login',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='middle_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workers',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
