# Generated by Django 4.1 on 2023-03-09 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_order_petid_remove_pets_pet_status_order_pet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
