# Generated by Django 4.1 on 2023-03-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_poster_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poster',
            name='date',
            field=models.DateField(),
        ),
    ]
