# Generated by Django 4.1 on 2023-03-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_actor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='actor',
            field=models.ManyToManyField(to='api.actor'),
        ),
    ]
