# Generated by Django 4.1 on 2023-03-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_status_alter_order_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Добавлен'), ('in_progress', 'Готовится'), ('ready', 'Готов'), ('served', 'Оплачен'), ('canceled', 'Отменен')], default='new', max_length=100),
        ),
    ]
