# Generated by Django 4.1 on 2023-03-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(choices=[('waiter', 'Официант'), ('cook', 'Повар'), ('manager', 'Администратор')], default='waiter', max_length=100),
        ),
    ]
