# Generated by Django 4.1 on 2023-03-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_position_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(choices=[('Официант', 'Официант'), ('Повар', 'Повар'), ('Администратор', 'Администратор')], default='waiter', max_length=100),
        ),
    ]
